// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(RazorPagesLibraryContext))]
    partial class RazorPagesLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("RazorPagesLibrary.Models.Library", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookAuthor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanedByName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanedTimes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnLoan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Library");
                });
#pragma warning restore 612, 618
        }
    }
}
